package org.design.model.common;

public enum Tag {
    EDUCATION,
    ENTERTAINMENT_ARTS,
    FINANCE_INSURANCE,
    GOVERNMENT_PUBLIC_SERVICE,
    HEALTH_FITNESS,
    HOTELS_ACCOMMODATION,
    NIGHTLIFE_DRINKS,
    RESTAURANTS_CAFES,
    SERVICES,
    SHOPPING_CONVENIENCE_STORES,
    TRANSPORTATION_AUTOMOTIVE,
    TRAVEL_TOURISM,
    LEGAL,
    BEAUTY_PERSONAL_CARE,
    PROPERTY,
    RELIGIOUS_PLACE,
    SPORTS_RECREATION,
    RETAIL_DELIVERY
}
